name = "worldcup-predict"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = true
routes = [
  { pattern = "wc-guess-2026.com", custom_domain = true },
  { pattern = "www.wc-guess-2026.com", custom_domain = true }
]

[triggers]
crons = ["0,30 * * * *"]

[vars]
FOOTBALL_API_TOKEN = "6a4ad18e3d4e4403ac2461e0fe98e53e"
ODDS_API_TOKEN = "47f7681ac41ca38a2c024c1928ca9343"
ANTHROPIC_API_KEY = "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"

[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "worldcup"
database_id = "f2d78b74-1150-40f0-986f-314fc6f70fe0"
